services:

  backend:
    image: back-despensa
    hostname: back-despensa
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    network_mode: "host"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # command: ./docker/bin/start_dev.sh
    # command: bash -c "sleep infinity"
    expose:
      - "8000"
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:13.3-alpine"
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      #- "./docker/postgres/pg_hba.conf:/usr/local/etc/postgres/postgres.conf"

  frontend:
    build:
      context: ./frontend
      args:
        NUXT_PUBLIC_PATH: http://localhost/static/
    image: front-despensa
    hostname: front-despensa
    command: npm run dev
    network_mode: "host"
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    depends_on:
      - nginx

  nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ./docker/nginx/default_local:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
