# Generated by Django 4.0.5 on 2023-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132)),
                ('price', models.FloatField()),
                ('target_quantity', models.IntegerField()),
                ('real_quantity', models.IntegerField()),
                ('type', models.CharField(choices=[('CONGELADOS', 'Congelados'), ('REFRIGERADOS', 'Refrigerados'), ('HORTIFRUTI', 'Hortifruti'), ('FRUTAS', 'Frutas'), ('SECOS', 'Secos'), ('LIMPEZA', 'Limpeza'), ('HIGIENE', 'Higiene')], default=False, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
