# Generated by Django 4.0.5 on 2023-02-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_despensausuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DespensaUsuario',
            new_name='UserStore',
        ),
    ]
